include_directories(../src)

add_executable(psijent-uniform psijent_uniform.c)
add_executable(psijent-stream psijent_stream.c)
add_executable(psijent-raw-deltas psijent_raw_deltas.c)

if (MSVC)
    target_link_libraries(psijent-uniform PRIVATE psijent_static)
    target_link_libraries(psijent-stream PRIVATE psijent_static)
    target_link_libraries(psijent-raw-deltas PRIVATE psijent_static)
else ()
    target_link_libraries(psijent-uniform PRIVATE psijent)
    target_link_libraries(psijent-stream PRIVATE psijent)
    target_link_libraries(psijent-raw-deltas PRIVATE psijent)
endif ()