set(PSIJENT_MEM_SIZE 16777216 CACHE STRING "Memory size")
set(PSIJENT_MEM_LOC_MASK 16777215 CACHE STRING "Memory location mask")
set(PSIJENT_MEM_MIN_JUMP_DIST 6291456 CACHE STRING "Minimum jump distance")
set(PSIJENT_MEM_RANDOMIZED_JUMP_MASK 2097151 CACHE STRING "Random jump mask")

set(PSIJENT_MEM_LOOP_COUNT 4096 CACHE STRING "Memory access loop count")

set(PSIJENT_MIN_WARMUP_CYCLES 1024 CACHE STRING "Minimum warm up cycles")
set(PSIJENT_MIN_WARMUP_DURATION_MILLIS 100 CACHE STRING "Minimum warm up duration in milliseconds")

option(PSIJENT_THROTTLE "Throttle to reduce CPU usage" ON)

set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

add_library(psijent SHARED psijent.cpp)
add_library(psijent_static psijent.cpp)

target_compile_definitions(psijent PUBLIC
        PSIJENT_MEM_SIZE=${PSIJENT_MEM_SIZE}
        PSIJENT_MEM_LOC_MASK=${PSIJENT_MEM_LOC_MASK}
        PSIJENT_MEM_MIN_JUMP_DIST=${PSIJENT_MEM_MIN_JUMP_DIST}
        PSIJENT_MEM_RANDOMIZED_JUMP_MASK=${PSIJENT_MEM_RANDOMIZED_JUMP_MASK}
        PSIJENT_MEM_LOOP_COUNT=${PSIJENT_MEM_LOOP_COUNT}
        PSIJENT_MIN_WARMUP_CYCLES=${PSIJENT_MIN_WARMUP_CYCLES}
        PSIJENT_MIN_WARMUP_DURATION_MILLIS=${PSIJENT_MIN_WARMUP_DURATION_MILLIS}
        PSIJENT_MANTISSA_BITS=${PSIJENT_MANTISSA_BITS}
        PSIJENT_THROTTLE=$<BOOL:${PSIJENT_THROTTLE}>
        PSIJENT_PRNG_XOR_MASKING=$<BOOL:${PSIJENT_PRNG_XOR_MASKING}>
)

target_compile_definitions(psijent_static PUBLIC
        PSIJENT_MEM_SIZE=${PSIJENT_MEM_SIZE}
        PSIJENT_MEM_LOC_MASK=${PSIJENT_MEM_LOC_MASK}
        PSIJENT_MEM_MIN_JUMP_DIST=${PSIJENT_MEM_MIN_JUMP_DIST}
        PSIJENT_MEM_RANDOMIZED_JUMP_MASK=${PSIJENT_MEM_RANDOMIZED_JUMP_MASK}
        PSIJENT_MEM_LOOP_COUNT=${PSIJENT_MEM_LOOP_COUNT}
        PSIJENT_MIN_WARMUP_CYCLES=${PSIJENT_MIN_WARMUP_CYCLES}
        PSIJENT_MIN_WARMUP_DURATION_MILLIS=${PSIJENT_MIN_WARMUP_DURATION_MILLIS}
        PSIJENT_MANTISSA_BITS=${PSIJENT_MANTISSA_BITS}
        PSIJENT_THROTTLE=$<BOOL:${PSIJENT_THROTTLE}>
        PSIJENT_PRNG_XOR_MASKING=$<BOOL:${PSIJENT_PRNG_XOR_MASKING}>
)

if (CMAKE_GENERATOR MATCHES "Makefiles")
    set_target_properties(psijent_static PROPERTIES OUTPUT_NAME psijent)
endif ()

install(TARGETS psijent psijent_static
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib)

install(FILES psijent.h DESTINATION include)
